### ISSUE TITLE
Demo page does not work

### ISSUE THREAD

**Issue by karloespiritu** [DaftMonk/angular-tour#68]
Demo page on - http://daftmonk.github.io/angular-tour/ does not work. The following error appears in the console log. Tested on Chrome, Firefox, and Safari:

Error: [$compile:ctreq] http://errors.angularjs.org/1.4.7/$compile/ctreq?p0=tour&p1=tourtip
    at Error (native)
    at http://daftmonk.github.io/angular-tour/lib/angular-1.4.7.min.js:6:416
    at t (http://daftmonk.github.io/angular-tour/lib/angular-1.4.7.min.js:59:233)
    at K (http://daftmonk.github.io/angular-tour/lib/angular-1.4.7.min.js:62:78)
    at g (http://daftmonk.github.io/angular-tour/lib/angular-1.4.7.min.js:54:410)
    at K (http://daftmonk.github.io/angular-tour/lib/angular-1.4.7.min.js:61:488)
    at g (http://daftmonk.github.io/angular-tour/lib/angular-1.4.7.min.js:54:410)
    at http://daftmonk.github.io/angular-tour/lib/angular-1.4.7.min.js:53:480
    at http://daftmonk.github.io/angular-tour/lib/angular-1.4.7.min.js:20:103
    at n.$eval (http://daftmonk.github.io/angular-tour/lib/angular-1.4.7.min.js:133:221)

**Comment by ashleydavis** [comment]
+1

I was keen to use this. I tried to integrate it into my website but it didn't work easily.

I thought I'd try the your demo to understand how it works, but your demo doesn't work either.

**Comment by nicolairobles** [comment]
I had the same issue and it has to do with the dependency paths not being correct and there are old dependencies. Very frustrating that the demo appears to be put together haphazardly.

You can spend time trying to untangle the mess, but what's quicker is to go to the demo site:
http://daftmonk.github.io/angular-tour/, then go to Sources in DevTools (in Chrome) and use the files in there. The only thing missing is the "tour.tpl.html" but that file is actually in the demo folder.

If you don't want to copy/paste b/c you're lazy you can use "httrack", which copies a page's source files for you through command line. >brew install httrack, >httrack <insert website>. This will download everything into the present working directory.
